[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false
maxMessageSize = 200
headless = true
runOnSave = true
port = 8501

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#00C2FF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1A1D"
textColor = "#FAFAFA"
font = "sans serif"

[runner]
magicEnabled = true
fastReruns = true

[client]
toolbarMode = "minimal"
showErrorDetails = true 