[firebase_credentials]
type = "service_account"
project_id = "pergunte-russel"
private_key_id = "93db4386e2"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCwZ7VkoD3rWG/t
2U5of9za8N6m2xMIcOPftAmzqoNBmeaDzBVezmFjMzPENg4HqdWNZ5np41G39LB/
hRpS6eYxejPBjY8aNpWRPpLGjNo0a5FSox05vO/f5lkP1+9mV7Wlu0RgtdnM6P3H
2OzYRJJ7cV0sfqZ8W2Nc3Nw/9aC/i/LaGoUxQ6sb5ZTyy5QVyeHI/nfmdDp6BQNF
XIHgowM/9ySv9w2LmHzqU6y90zN9WSbs5wMl4sigedw7xXIPan8ipnbGkuw4cNM/
ikoc13w1+GN/1JezXVDwO1K2ueAKXjm/TOrlDhJXH1F559Hpousg705ZJrVcipvn
Sp+KoV/DAgMBAAECggEAPslK2LvoDgH2JLP5olwQIaUlukGzLofvs0mDQn1oJks+
rp5O5OWT6BjrTeTnbXbXWXMMZyDPjyf6Qgj/647wrZ+PGE7oJi5TYdThrOWpLIs0
uDLyTgCfaBO2k1sKDGUfdBOJLNrM4I/089KTyg3uDR22SgXx/8UPQpghlGo6grIV
46J+YiiaFmIglfXzy/vaFQznL7iTC4/2thI0hZSTLMYax9H5yJsHj2HRth+VhegI
QlI9wc1NE711tWsaIW/VS0VG3nlH+hKsTEnFFHnOVQkH8ImAjv+54sLenWeJ1O8v
99rK+DJQrPwhDaJ2YtiewVWYuIKWHLvCLXSfqdBAoQKBgQD4nz+C+A6sIxY56FqN
iBCS3ZjqiIdZz16EZ5Abiu0BtnDlLScTWlgrAGNWmrysrtQzneV/QuudUnsksbd0
qi6V4l0aaTLi1bUKPyhX7bnnyKkrGfX+XtqQV6VGzRBUmLHtLX2imSQ73T4er4se
2FdxVyR82W9qbhDxUMGx2YdjWwKBgQC1o9ZEcE/huVnTdMg8EVxDNdyEbS7ZpCRl
eFvKfnALOWTNMo5JOiHJOmnWnA+SiJICOwaxyHXlvAXxyMc08cG7FCOr6dR5pNEu
nknUhvh/bwzr3SaPZ0CyIDSTE4ptpyzkj2iog26lbRL64xU1eohpojwk82B5fpOq
tNa0xXMpuQKBgQDL3HiNga02RMby0K1/o/RDGOVMWorxf3I3C1xE2VOhteE4ah/C
ZLArAnRyDQtsZSam9G+8PDlKlNlYq0iMpwbv697/ywborOd38XW5M7rebdEZAH6P
B2QcO2HQflFHrLUoj8aWzw/A7pcDPlnK/wYkb5oBraEIGhxWYyuQE5hKRQKBgQCX
04a6VhavWrrWoXrtmqVAGLlmh8ztZuJ1XpF7RQxqlWLIkkWUt96d0RG+rVvm4/kH
nEcQO7sweGWPoH/CpYGF2mOmwyEzPK0NBoo390mnWy+1x3j/zRKq0Xigp2jCF0bT
FXwpvxKxe+athzqnJPD5Ov6C9FvjsgXEXrxJBfIpIQKBgG+T1b8fjR8dSqDcaX1Q
8X3B/uLBA81zouhuxtwK99qqx0qspH2zA5/Hhy7aoLgEdhlGs8ZZ9DWqM2fayUsG
wbvSJLsC95mV2TpYkZqxxqXChb2j7KY0Wp3Pw8pYk6gPQ1AwgDhz/HyJrxxx5quP
oGf0Mmb8fFFTw18wmbUj4VFV
-----END PRIVATE KEY-----'''
client_email = "firebase-adminsdk-fbsvc@pergunte-russel.iam.gserviceaccount.com"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40pergunte-russel.iam.gserviceaccount.com" 
